version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/todos
      - APP_PORT=80
    ports: ['80:80']
  db:
    container_name: db
    image: mongo:4.0
    restart: always
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '8080:8080'
  nginx:
    build:
      context: ./nginx-gateway
    container_name: nginx
    ports:
      - '8000:8000'
    volumes:
      - ./nginx-gateway:/etc/nginx/conf.d
    depends_on:
      - backend
