version: "3"
services:
  go:
    container_name: go
    build: ./go
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn"
    ports: ['8080:8080']
    volumes:
      - ./go/Demo:/root
    command: /bin/bash -c "go build -o demo &&./demo" 
    networks:
      kong-net:
        ipv4_address: 172.18.0.8

  node:
    container_name: node
    build: ./node
    ports: ['8081:8080']
    volumes:
      - ./node/Demo/:/root/
    command: /bin/bash -c "npm install && npm start"
    networks:
      kong-net:
        ipv4_address: 172.18.0.9

networks:
  kong-net:
    ipam:
      config:
        - subnet: 172.18.0.0/24
